@startuml

left to right direction
actor Utilisateur

package "Système de Réservation de Véhicules" {
    usecase "Réserver un véhicule" as UC1
    usecase "Consulter les véhicules disponibles" as UC2
    usecase "Annuler une réservation" as UC3
    usecase "Signaler un dommage" as UC4
    usecase "Choisir un type de véhicule" as UC5
    usecase "Choisir une période de temps" as UC6
    usecase "Sélectionner une station" as UC7
    usecase "Voir les alternatives" as UC8
}

Utilisateur --> UC1
Utilisateur --> UC2
Utilisateur --> UC3

UC1 ..> UC5 : include
UC1 ..> UC6 : include
UC1 ..> UC7 : include
UC1 ..> UC2 : include

UC8 .u.|> UC1 : extends
UC4 .u.|> UC1 : extends


@enduml
